/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.dac.telas;

import br.edu.ifpb.dac.gerenciador.Gerenciador;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author Fernando
 */
public class JanelaFuncionario extends java.awt.Dialog {

    Gerenciador gerenciador = Gerenciador.getInstance();
    private Dialog thisDialog;
    private TrataBotao tb;

    /**
     * Creates new form JanelaFuncionario
     */
    public JanelaFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.tb = new TrataBotao();
        this.btCadastrarClientes.addActionListener(tb);
        this.btCadastrarFuncionario.addActionListener(tb);
        this.btCadastrarFornecedor.addActionListener(tb);
        this.btCadastrarMaterial.addActionListener(tb);
        this.btBuscarCliente.addActionListener(tb);
        this.btRealizarVenda.addActionListener(tb);
        this.btCadastrarProduto.addActionListener(tb);
        this.btBuscarCliente.addActionListener(tb);
        this.btBuscarProduto.addActionListener(tb);
        this.btBuscarVendas.addActionListener(tb);
        this.btSair.addActionListener(tb);
        lbNomeFuncionario.setText(gerenciador.getFuncionario().getNome());
        thisDialog = this;
        this.verificarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNomeFuncionario = new javax.swing.JLabel();
        panelSecundario = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btCadastrarClientes = new javax.swing.JButton();
        btCadastrarFuncionario = new javax.swing.JButton();
        btCadastrarFornecedor = new javax.swing.JButton();
        btRealizarVenda = new javax.swing.JButton();
        btBuscarCliente = new javax.swing.JButton();
        btCadastrarMaterial = new javax.swing.JButton();
        btCadastrarProduto = new javax.swing.JButton();
        btBuscarProduto = new javax.swing.JButton();
        btBuscarVendas = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNomeFuncionario.setText("Nome do Funcionário");
        jPanel1.add(lbNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 30));

        panelSecundario.setMinimumSize(new java.awt.Dimension(600, 750));
        jPanel1.add(panelSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 620, 740));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 10, 740));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCadastrarClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCadastrarClientes.setText("Cadastrar Clientes");
        btCadastrarClientes.setToolTipText("Cadastrar novos clientes no sistema");
        btCadastrarClientes.setMaximumSize(new java.awt.Dimension(250, 31));
        btCadastrarClientes.setMinimumSize(new java.awt.Dimension(230, 31));
        jPanel2.add(btCadastrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));

        btCadastrarFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCadastrarFuncionario.setText("Cadastrar Funcionário");
        btCadastrarFuncionario.setMaximumSize(new java.awt.Dimension(250, 31));
        btCadastrarFuncionario.setMinimumSize(new java.awt.Dimension(250, 31));
        btCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jPanel2.add(btCadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, -1));

        btCadastrarFornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jPanel2.add(btCadastrarFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, -1));

        btRealizarVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRealizarVenda.setText("Realizar Venda");
        btRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarVendaActionPerformed(evt);
            }
        });
        jPanel2.add(btRealizarVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, -1));

        btBuscarCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btBuscarCliente.setText("Buscar/Editar Cliente");
        btBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        btCadastrarMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCadastrarMaterial.setText("Cadastrar Material");
        btCadastrarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarMaterialActionPerformed(evt);
            }
        });
        jPanel2.add(btCadastrarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, -1));

        btCadastrarProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCadastrarProduto.setText("Cadastrar Produto");
        btCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(btCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, -1));

        btBuscarProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btBuscarProduto.setText("Buscar/Editar Produto");
        jPanel2.add(btBuscarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, -1));

        btBuscarVendas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btBuscarVendas.setText("Buscar Vendas");
        jPanel2.add(btBuscarVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 720));

        btSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSair.setForeground(new java.awt.Color(255, 0, 0));
        btSair.setText("Sair");
        jPanel1.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        gerenciador.setFuncionario(null);
    }//GEN-LAST:event_closeDialog

    private void btCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarProdutoActionPerformed

    private void btCadastrarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarMaterialActionPerformed

    private void btBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarClienteActionPerformed

    private void btRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRealizarVendaActionPerformed

    private void btCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarFuncionarioActionPerformed
    private void verificarBotoes() {
        if ((long) gerenciador.getSingleResultOfNamedQuery("Produto.getQuantidade") == 0) {
            btBuscarProduto.setEnabled(false);
            btRealizarVenda.setEnabled(false);
        }

        if ((long) gerenciador.getSingleResultOfNamedQuery("Vendas.quantidade") == 0) {
            btBuscarVendas.setEnabled(false);
        }
        if ((long) gerenciador.getSingleResultOfNamedQuery("Material.getQuantidade") == 0
                || (long) gerenciador.getSingleResultOfNamedQuery("Fornecedor.getQuantidade") == 0) {
            btCadastrarProduto.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarCliente;
    private javax.swing.JButton btBuscarProduto;
    private javax.swing.JButton btBuscarVendas;
    private javax.swing.JButton btCadastrarClientes;
    private javax.swing.JButton btCadastrarFornecedor;
    private javax.swing.JButton btCadastrarFuncionario;
    private javax.swing.JButton btCadastrarMaterial;
    private javax.swing.JButton btCadastrarProduto;
    private javax.swing.JButton btRealizarVenda;
    private javax.swing.JButton btSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbNomeFuncionario;
    private javax.swing.JPanel panelSecundario;
    // End of variables declaration//GEN-END:variables

    private class TrataBotao implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource().equals(btCadastrarClientes)) {
                this.chamarNovoPainel(new PanelCadastrarClientes());
            } else if (e.getSource().equals(btCadastrarFuncionario)) {
                this.chamarNovoPainel(new PanelCadastrarFuncionario());
            } else if (e.getSource().equals(btCadastrarFornecedor)) {
                this.chamarNovoPainel(new PanelCadastrarFornecedor());
            } else if (e.getSource().equals(btCadastrarMaterial)) {
                this.chamarNovoPainel(new PanelCadastrarMaterial());
            } else if (e.getSource().equals(btBuscarCliente)) {
                this.chamarNovoPainel(new PainelBuscarCliente());
            } else if (e.getSource().equals(btRealizarVenda)) {
                new JanelaRealizarVenda(null, true).setVisible(true);
            } else if (e.getSource().equals(btCadastrarProduto)) {
                this.chamarNovoPainel(new PanelCadastrarProduto());
            } else if (e.getSource().equals(btBuscarProduto)) {
                this.chamarNovoPainel(new PainelBuscarProduto());
            } else if (e.getSource().equals(btBuscarVendas)) {
                new JanelaBuscarVendas(null, true).setVisible(true);
            } else if (e.getSource().equals(btSair)) {
                setVisible(false);
                dispose();
                gerenciador.setFuncionario(null);
            }
        }

        private void chamarNovoPainel(JPanel jPanel) {
            panelSecundario.removeAll();
            jPanel.setVisible(true);
            panelSecundario.add(jPanel);
            panelSecundario.revalidate();
            panelSecundario.validate();
        }

    }

}
