/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.dac.telas;

import br.edu.ifpb.dac.beans.Fornecedor;
import br.edu.ifpb.dac.beans.Material;
import br.edu.ifpb.dac.beans.Produto;
import br.edu.ifpb.dac.exceptions.ErroAconteceuException;
import br.edu.ifpb.dac.executaImagem.CarregaArquivo;
import br.edu.ifpb.dac.gerenciador.Gerenciador;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.activation.MimetypesFileTypeMap;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Fernando
 */
public class PanelCadastrarProduto extends javax.swing.JPanel {

    private Gerenciador gerenciador = Gerenciador.getInstance();
    private TrataBotao tb;
    private JDialog parent;
    private List<JTextField> textFields = new ArrayList();
    private List<Component> components;
    private List<Material> materiais = gerenciador.getListResultOfNamedQuery("Material.findAll");
    private DefaultListModel defaultListMateriais;
    private List<Fornecedor> fornecedores = gerenciador.getListResultOfNamedQuery("Fornecedor.findAll");

    /**
     * Creates new form CadastrarBotao
     */
    public PanelCadastrarProduto() {
        initComponents();
        this.tb = new TrataBotao();
        this.defaultListMateriais = new DefaultListModel();
        this.btCadastrar.addActionListener(tb);
        this.btEscolhetImagem.addActionListener(tb);
        for (Material material : materiais) {
            this.defaultListMateriais.addElement(material);
        }
        this.listMaterial.setModel(defaultListMateriais);

        for (Fornecedor fornecedor : fornecedores) {
            this.comboBoxFornecedores.addItem(fornecedor);
        }

        parent = (JDialog) this.getParent();
        components = Arrays.asList(painelMaior.getComponents());
        for (Component component : components) {
            if (component instanceof JTextField) {
                textFields.add((JTextField) component);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        painelMaior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldMarca = new javax.swing.JTextField();
        Tamamnho = new javax.swing.JLabel();
        fieldQuantidade = new javax.swing.JTextField();
        fieldTamanho = new javax.swing.JFormattedTextField();
        Tamamnho1 = new javax.swing.JLabel();
        fieldCodigo = new javax.swing.JTextField();
        Tamamnho2 = new javax.swing.JLabel();
        fieldCaminhoImagem = new javax.swing.JTextField();
        Tamamnho3 = new javax.swing.JLabel();
        fieldValor = new javax.swing.JTextField();
        btEscolhetImagem = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMaterial = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxFornecedores = new javax.swing.JComboBox();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Novo Produto");

        painelMaior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Quantidade disponível:");
        painelMaior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");
        painelMaior.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        fieldNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });
        painelMaior.add(fieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 510, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Código:");
        painelMaior.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        fieldMarca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMarcaActionPerformed(evt);
            }
        });
        painelMaior.add(fieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 190, -1));

        Tamamnho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tamamnho.setText("Marca:");
        painelMaior.add(Tamamnho, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        fieldQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQuantidadeActionPerformed(evt);
            }
        });
        painelMaior.add(fieldQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 130, -1));

        fieldTamanho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelMaior.add(fieldTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 40, -1));

        Tamamnho1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tamamnho1.setText("Iamgem:");
        painelMaior.add(Tamamnho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        fieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodigoActionPerformed(evt);
            }
        });
        painelMaior.add(fieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 180, -1));

        Tamamnho2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tamamnho2.setText("Valor R$");
        painelMaior.add(Tamamnho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        fieldCaminhoImagem.setEditable(false);
        fieldCaminhoImagem.setBackground(new java.awt.Color(235, 235, 255));
        fieldCaminhoImagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldCaminhoImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCaminhoImagemActionPerformed(evt);
            }
        });
        painelMaior.add(fieldCaminhoImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 320, -1));

        Tamamnho3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tamamnho3.setText("Tamanho:");
        painelMaior.add(Tamamnho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        fieldValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });
        painelMaior.add(fieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 100, -1));

        btEscolhetImagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btEscolhetImagem.setText("Escolher Imagem");
        btEscolhetImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscolhetImagemActionPerformed(evt);
            }
        });
        painelMaior.add(btEscolhetImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        painelMaior.add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        listMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(listMaterial);

        painelMaior.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 500, 200));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fornecedor:");
        painelMaior.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Material:");
        painelMaior.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        comboBoxFornecedores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxFornecedores.setToolTipText("");
        painelMaior.add(comboBoxFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 480, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(painelMaior, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(painelMaior, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void fieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMarcaActionPerformed

    private void fieldQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQuantidadeActionPerformed

    private void fieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodigoActionPerformed

    private void fieldCaminhoImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCaminhoImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCaminhoImagemActionPerformed

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValorActionPerformed

    private void btEscolhetImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolhetImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEscolhetImagemActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tamamnho;
    private javax.swing.JLabel Tamamnho1;
    private javax.swing.JLabel Tamamnho2;
    private javax.swing.JLabel Tamamnho3;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEscolhetImagem;
    private javax.swing.JComboBox comboBoxFornecedores;
    private javax.swing.JTextField fieldCaminhoImagem;
    private javax.swing.JTextField fieldCodigo;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldQuantidade;
    private javax.swing.JFormattedTextField fieldTamanho;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMaterial;
    private javax.swing.JPanel painelMaior;
    // End of variables declaration//GEN-END:variables

    private class TrataBotao implements ActionListener {

        private String caminhoArquivo;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource().equals(btEscolhetImagem)) {
                try {
                    JFileChooser escolherArquivo = new JFileChooser();
                    escolherArquivo.addChoosableFileFilter(new FileNameExtensionFilter("Arquivos de Imagem", "jpg", "png", "bmp", "jpeg", "gif"));
                    escolherArquivo.showOpenDialog(null);
                    caminhoArquivo = escolherArquivo.getSelectedFile().getAbsolutePath();
                    if (CarregaArquivo.arquivoAceitavel(caminhoArquivo) == false) {
                        fieldCaminhoImagem.setText(null);
                        throw new ErroAconteceuException("Tipo de Arquivo não aceito");
                    }
                    fieldCaminhoImagem.setText(caminhoArquivo);
                } catch (ErroAconteceuException ex) {
                    JOptionPane jOptionPane = new JOptionPane(ex.getMessage(), JOptionPane.WARNING_MESSAGE);
                    parent = jOptionPane.createDialog("Erro");
                    parent.setVisible(true);
                }
            } else if (e.getSource().equals(btCadastrar)) {
                try {
                    if (fieldNome.getText() == null || fieldNome.getText().isEmpty()) {
                        throw new ErroAconteceuException("Por favor, Infomrme o Nome do Produto");
                    } else if (fieldCodigo.getText() == null || fieldCodigo.getText().isEmpty()) {
                        throw new ErroAconteceuException("Por favor, Informe o Código do Produto");
                    } else if (fieldQuantidade.getText() == null || fieldQuantidade.getText().isEmpty()
                            || !this.verificaNumeros(fieldQuantidade.getText())) {
                        throw new ErroAconteceuException("Por favor, Informe uma quantidade válida para o produto");
                    } else if (fieldTamanho.getText() == null || fieldTamanho.getText().isEmpty()
                            || !this.verificaNumeros(fieldTamanho.getText())) {
                        throw new ErroAconteceuException("Por favor, Informe um  tamanho válido para o produto");
                    } else if (fieldValor.getText() == null || fieldValor.getText().isEmpty()) {
                        throw new ErroAconteceuException("Por favor, Informe valor válido para o produto");
                    } else if (fieldMarca.getText() == null || fieldMarca.getText().isEmpty()) {
                        throw new ErroAconteceuException("Por favor, Informe a marca");
                    } else if (fieldCaminhoImagem.getText().isEmpty()) {
                        throw new ErroAconteceuException("Por favor, Selecione uma imagem para o produto");
                    }

                    int quantidade = Integer.parseInt(fieldQuantidade.getText());
                    if (quantidade <= 0) {
                        throw new ErroAconteceuException("Por favor, Informe uma quantidade válida para o produto");
                    }

                    int tamanho = Integer.parseInt(fieldTamanho.getText());
                    if (tamanho <= 0) {
                        throw new ErroAconteceuException("Por favor, Informe um  tamanho válido para o produto");
                    }

                    String valorInformado = fieldValor.getText();
                    valorInformado = valorInformado.replace(",", ".");
                    double valor = Double.parseDouble(valorInformado);
                    if (valor <= 0) {
                        throw new ErroAconteceuException("Por favor, Informe valor válido para o produto");
                    }

                    //Criando objeto produto
                    Produto produto = new Produto();
                    produto.setDescricao(fieldNome.getText());
                    produto.setCodigo(fieldCodigo.getText());
                    produto.setQuantidade(quantidade);
                    produto.setTamanho(tamanho);
                    produto.setValor(valor);
                    produto.setMarca(fieldMarca.getText());
                    produto.setImagem(CarregaArquivo.carregaArquivo(caminhoArquivo));
                    List<Material> materiaisSelecionandos = (List<Material>) listMaterial.getSelectedValuesList();
                    produto.setFornecedor((Fornecedor) comboBoxFornecedores.getSelectedItem());
                    produto.addMateriais(materiaisSelecionandos);

                    //Salvando produto
                    if (gerenciador.save(produto)) {
                        JOptionPane jOptionPane = new JOptionPane("Produto cadastrado com sucesso");
                        parent = jOptionPane.createDialog("Sucesso");
                        parent.setVisible(true);
                        for (JTextField jTextField : textFields) {
                            jTextField.setText("");
                        }
                        listMaterial.setSelectedIndex(-1);
                    } else {
                        JOptionPane jOptionPane = new JOptionPane("Novo Produto não pôde ser cadastrado");
                        parent = jOptionPane.createDialog("Erro");
                        parent.setVisible(true);
                    }
                } catch (ErroAconteceuException ex) {
                    JOptionPane jOptionPane = new JOptionPane(ex.getMessage(), JOptionPane.WARNING_MESSAGE);
                    parent = jOptionPane.createDialog("Erro");
                    parent.setVisible(true);
                } catch (NumberFormatException ex) {
                    JOptionPane jOptionPane = new JOptionPane("Erro ocorrido por favor verifique suas informações", JOptionPane.WARNING_MESSAGE);
                    parent = jOptionPane.createDialog("Erro");
                    parent.setVisible(true);
                }
            }

        }

        private boolean verificaNumeros(String numero) {
            Pattern pattern = Pattern.compile("^\\d+$");
            Matcher matcher = pattern.matcher(numero);
            return matcher.matches();
        }

    }
}
